AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Unplugd — Serverless karaoke backend.
  Upload songs, separate stems with Demucs, extract synced lyrics with Whisper.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment

  AppName:
    Type: String
    Default: unplugd
    Description: Application name used for resource naming

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 256
    Timeout: 30
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        APP_NAME: !Ref AppName
        SONGS_TABLE_NAME: !GetAtt StorageStack.Outputs.SongsTableName
        CONNECTIONS_TABLE_NAME: !GetAtt StorageStack.Outputs.ConnectionsTableName
        UPLOAD_BUCKET_NAME: !Sub "${AppName}-${Environment}-uploads-${AWS::AccountId}"
        OUTPUT_BUCKET_NAME: !GetAtt StorageStack.Outputs.OutputBucketName
        COGNITO_USER_POOL_ID: !GetAtt AuthStack.Outputs.UserPoolId
        COGNITO_APP_CLIENT_ID: !GetAtt AuthStack.Outputs.UserPoolClientId
        DLQ_URL: !GetAtt MonitoringStack.Outputs.DeadLetterQueueUrl

Resources:
  # ---- S3 Upload Bucket (root-level for SAM S3 event source) ----

  UploadBucket:
    Type: AWS::S3::Bucket
    DependsOn: ProcessUploadInvokePermission
    Properties:
      BucketName: !Sub "${AppName}-${Environment}-uploads-${AWS::AccountId}"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt ProcessUploadFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
      LifecycleConfiguration:
        Rules:
          - Id: ExpireUploadsAfter24Hours
            Status: Enabled
            ExpirationInDays: 1
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
            AllowedOrigins:
              - "*"
            MaxAge: 3600
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref AppName

  ProcessUploadInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ProcessUploadFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${AppName}-${Environment}-uploads-${AWS::AccountId}"
      SourceAccount: !Ref AWS::AccountId

  # ---- Nested Stacks ----

  StorageStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/storage.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName

  AuthStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/auth.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName

  MonitoringStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/monitoring.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName

  # ---- Lambda Layer ----

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AppName}-${Environment}-common"
      Description: Shared Python libraries (mutagen, python-ulid)
      ContentUri: layers/common/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.12

  # ---- Phase 2: Upload Lambda Functions ----

  UploadRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-upload-request"
      Handler: upload_request/handler.lambda_handler
      CodeUri: functions/
      Layers:
        - !Ref CommonLayer
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub "${AppName}-${Environment}-uploads-${AWS::AccountId}"
        - DynamoDBCrudPolicy:
            TableName: !GetAtt StorageStack.Outputs.SongsTableName

  ProcessUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-process-upload"
      Handler: process_upload/handler.lambda_handler
      CodeUri: functions/
      Timeout: 60
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          STATE_MACHINE_ARN: ""
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "${AppName}-${Environment}-uploads-${AWS::AccountId}"
        - DynamoDBCrudPolicy:
            TableName: !GetAtt StorageStack.Outputs.SongsTableName

  # ---- Phase 2: REST API ----

  ApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/api.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName
        CognitoUserPoolArn: !GetAtt AuthStack.Outputs.UserPoolArn
        UploadRequestFunctionArn: !GetAtt UploadRequestFunction.Arn

  # ---- Phase 3: WebSocket Lambda Functions ----

  WsConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-ws-connect"
      Handler: ws_connect/handler.lambda_handler
      CodeUri: functions/
      Layers:
        - !Ref CommonLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !GetAtt StorageStack.Outputs.ConnectionsTableName

  WsDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-ws-disconnect"
      Handler: ws_disconnect/handler.lambda_handler
      CodeUri: functions/
      Layers:
        - !Ref CommonLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !GetAtt StorageStack.Outputs.ConnectionsTableName

  WsDefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-ws-default"
      Handler: ws_default/handler.lambda_handler
      CodeUri: functions/
      Layers:
        - !Ref CommonLayer

  SendProgressFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-send-progress"
      Handler: send_progress/handler.lambda_handler
      CodeUri: functions/
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          WEBSOCKET_API_ENDPOINT: !GetAtt WebSocketStack.Outputs.WebSocketManagementEndpoint
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !GetAtt StorageStack.Outputs.ConnectionsTableName
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketStack.Outputs.WebSocketApiId}/*"

  # ---- Phase 3: WebSocket API ----

  WebSocketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/websocket.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName
        WsConnectFunctionArn: !GetAtt WsConnectFunction.Arn
        WsDisconnectFunctionArn: !GetAtt WsDisconnectFunction.Arn
        WsDefaultFunctionArn: !GetAtt WsDefaultFunction.Arn

  # ---- Phase 4: VPC + ECS/Fargate ----

  VpcStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/vpc.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName

  EcsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/ecs.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName
        UploadBucketName: !Sub "${AppName}-${Environment}-uploads-${AWS::AccountId}"
        OutputBucketName: !GetAtt StorageStack.Outputs.OutputBucketName
        SendProgressFunctionArn: !GetAtt SendProgressFunction.Arn

  # Phase 5: Whisper ECR repo, task definition
  # Phase 6: Step Functions state machine, Lambda functions
  # Phase 7: Song library API routes
  # Phase 9: CloudWatch dashboard, alarms

Outputs:
  StackName:
    Description: CloudFormation stack name
    Value: !Ref AWS::StackName
  Environment:
    Description: Deployment environment
    Value: !Ref Environment

  # Storage
  SongsTableName:
    Value: !GetAtt StorageStack.Outputs.SongsTableName
  SongsTableArn:
    Value: !GetAtt StorageStack.Outputs.SongsTableArn
  ConnectionsTableName:
    Value: !GetAtt StorageStack.Outputs.ConnectionsTableName
  ConnectionsTableArn:
    Value: !GetAtt StorageStack.Outputs.ConnectionsTableArn
  UploadBucketName:
    Value: !Sub "${AppName}-${Environment}-uploads-${AWS::AccountId}"
  UploadBucketArn:
    Value: !Sub "arn:aws:s3:::${AppName}-${Environment}-uploads-${AWS::AccountId}"
  OutputBucketName:
    Value: !GetAtt StorageStack.Outputs.OutputBucketName
  OutputBucketArn:
    Value: !GetAtt StorageStack.Outputs.OutputBucketArn
  # Auth
  CognitoUserPoolId:
    Value: !GetAtt AuthStack.Outputs.UserPoolId
  CognitoUserPoolArn:
    Value: !GetAtt AuthStack.Outputs.UserPoolArn
  CognitoUserPoolClientId:
    Value: !GetAtt AuthStack.Outputs.UserPoolClientId

  # Monitoring
  DeadLetterQueueUrl:
    Value: !GetAtt MonitoringStack.Outputs.DeadLetterQueueUrl
  DeadLetterQueueArn:
    Value: !GetAtt MonitoringStack.Outputs.DeadLetterQueueArn

  # API
  ApiEndpoint:
    Value: !GetAtt ApiStack.Outputs.ApiEndpoint

  # WebSocket
  WebSocketApiEndpoint:
    Value: !GetAtt WebSocketStack.Outputs.WebSocketApiEndpoint
  SendProgressFunctionArn:
    Value: !GetAtt SendProgressFunction.Arn

  # VPC
  VpcId:
    Value: !GetAtt VpcStack.Outputs.VpcId
  PublicSubnetIds:
    Value: !GetAtt VpcStack.Outputs.PublicSubnetIds
  FargateSecurityGroupId:
    Value: !GetAtt VpcStack.Outputs.FargateSecurityGroupId

  # ECS
  DemucsRepositoryUri:
    Value: !GetAtt EcsStack.Outputs.DemucsRepositoryUri
  EcsClusterArn:
    Value: !GetAtt EcsStack.Outputs.EcsClusterArn
  DemucsTaskDefinitionArn:
    Value: !GetAtt EcsStack.Outputs.DemucsTaskDefinitionArn
