AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Unplugd — Serverless karaoke backend.
  Upload songs, separate stems with Demucs, extract synced lyrics with Whisper.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment

  AppName:
    Type: String
    Default: unplugd
    Description: Application name used for resource naming

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 256
    Timeout: 30
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        APP_NAME: !Ref AppName
        SONGS_TABLE_NAME: !GetAtt StorageStack.Outputs.SongsTableName
        CONNECTIONS_TABLE_NAME: !GetAtt StorageStack.Outputs.ConnectionsTableName
        UPLOAD_BUCKET_NAME: !GetAtt StorageStack.Outputs.UploadBucketName
        OUTPUT_BUCKET_NAME: !GetAtt StorageStack.Outputs.OutputBucketName
        CLOUDFRONT_DOMAIN: !GetAtt StorageStack.Outputs.CloudFrontDomainName
        COGNITO_USER_POOL_ID: !GetAtt AuthStack.Outputs.UserPoolId
        DLQ_URL: !GetAtt MonitoringStack.Outputs.DeadLetterQueueUrl

Resources:
  # ---- Nested Stacks ----

  StorageStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/storage.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName

  AuthStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/auth.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName

  MonitoringStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/monitoring.yaml
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName

  # Phase 2: REST API, upload Lambda functions, CommonLayer
  # Phase 3: WebSocket API, WS Lambda functions
  # Phase 4: ECR repo, ECS Cluster, Demucs task definition
  # Phase 5: Whisper ECR repo, task definition
  # Phase 6: Step Functions state machine, VPC, Lambda functions
  # Phase 7: Song library API routes
  # Phase 9: CloudWatch dashboard, alarms

Outputs:
  StackName:
    Description: CloudFormation stack name
    Value: !Ref AWS::StackName
  Environment:
    Description: Deployment environment
    Value: !Ref Environment

  # Storage
  SongsTableName:
    Value: !GetAtt StorageStack.Outputs.SongsTableName
  SongsTableArn:
    Value: !GetAtt StorageStack.Outputs.SongsTableArn
  ConnectionsTableName:
    Value: !GetAtt StorageStack.Outputs.ConnectionsTableName
  ConnectionsTableArn:
    Value: !GetAtt StorageStack.Outputs.ConnectionsTableArn
  UploadBucketName:
    Value: !GetAtt StorageStack.Outputs.UploadBucketName
  UploadBucketArn:
    Value: !GetAtt StorageStack.Outputs.UploadBucketArn
  OutputBucketName:
    Value: !GetAtt StorageStack.Outputs.OutputBucketName
  OutputBucketArn:
    Value: !GetAtt StorageStack.Outputs.OutputBucketArn
  CloudFrontDomainName:
    Value: !GetAtt StorageStack.Outputs.CloudFrontDomainName
  CloudFrontDistributionId:
    Value: !GetAtt StorageStack.Outputs.CloudFrontDistributionId

  # Auth
  CognitoUserPoolId:
    Value: !GetAtt AuthStack.Outputs.UserPoolId
  CognitoUserPoolArn:
    Value: !GetAtt AuthStack.Outputs.UserPoolArn
  CognitoUserPoolClientId:
    Value: !GetAtt AuthStack.Outputs.UserPoolClientId

  # Monitoring
  DeadLetterQueueUrl:
    Value: !GetAtt MonitoringStack.Outputs.DeadLetterQueueUrl
  DeadLetterQueueArn:
    Value: !GetAtt MonitoringStack.Outputs.DeadLetterQueueArn
