AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Unplugd — REST API Gateway with Cognito authorizer"

Parameters:
  Environment:
    Type: String
  AppName:
    Type: String
  CognitoUserPoolArn:
    Type: String
  UploadRequestFunctionArn:
    Type: String
  CorsOrigin:
    Type: String
  ListSongsFunctionArn:
    Type: String
  GetSongFunctionArn:
    Type: String
  DeleteSongFunctionArn:
    Type: String
  GetPresetsFunctionArn:
    Type: String

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AppName}-${Environment}-api"
      StageName: !Ref Environment
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
      Cors:
        AllowOrigin: !Sub "'${CorsOrigin}'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      DefinitionBody:
        swagger: "2.0"
        info:
          title: !Sub "${AppName}-${Environment}-api"
          version: "1.0"
        paths:
          /songs/upload-url:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UploadRequestFunctionArn}/invocations"
                httpMethod: POST
                type: aws_proxy
              security:
                - CognitoAuthorizer: []
              responses:
                "201":
                  description: "Upload URL created"
          /songs:
            get:
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListSongsFunctionArn}/invocations"
                httpMethod: POST
                type: aws_proxy
              security:
                - CognitoAuthorizer: []
              responses:
                "200":
                  description: "Song list"
          /songs/{songId}:
            get:
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetSongFunctionArn}/invocations"
                httpMethod: POST
                type: aws_proxy
              security:
                - CognitoAuthorizer: []
              responses:
                "200":
                  description: "Song detail"
            delete:
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteSongFunctionArn}/invocations"
                httpMethod: POST
                type: aws_proxy
              security:
                - CognitoAuthorizer: []
              responses:
                "200":
                  description: "Song deleted"
          /presets:
            get:
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetPresetsFunctionArn}/invocations"
                httpMethod: POST
                type: aws_proxy
              security:
                - CognitoAuthorizer: []
              responses:
                "200":
                  description: "Preset list"
        securityDefinitions:
          CognitoAuthorizer:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: cognito_user_pools
            x-amazon-apigateway-authorizer:
              type: cognito_user_pools
              providerARNs:
                - !Ref CognitoUserPoolArn

  UploadRequestInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UploadRequestFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*"

  ListSongsInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ListSongsFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*"

  GetSongInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetSongFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*"

  DeleteSongInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeleteSongFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*"

  GetPresetsInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetPresetsFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*"

Outputs:
  ApiId:
    Value: !Ref RestApi
  ApiEndpoint:
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
